/**
 * Public API surface — re-exports from client and types.
 */

export {
  ApiError,
  apiFetch,
  createButlerSchedule,
  deleteButlerSchedule,
  deleteButlerState,
  getButler,
  getButlerConfig,
  getButlerNotifications,
  getButlerSchedules,
  getButlerSession,
  getButlerSessions,
  getButlerSkills,
  getButlerState,
  getButlers,
  getCostSummary,
  getDailyCosts,
  getHealth,
  getIssues,
  getNotifications,
  getNotificationStats,
  getSession,
  getSessions,
  getTimeline,
  getTopSessions,
  searchAll,
  getTrace,
  getTraces,
  setButlerState,
  toggleButlerSchedule,
  triggerButler,
  updateButlerSchedule,
} from "./client.ts";

export type {
  ApiMeta,
  ApiResponse,
  ButlerConfigResponse,
  ButlerSkill,
  ButlerSummary,
  CostSummary,
  DailyCost,
  ErrorDetail,
  ErrorResponse,
  HealthResponse,
  Issue,
  NotificationParams,
  NotificationStats,
  NotificationSummary,
  PaginatedResponse,
  PaginationMeta,
  Schedule,
  ScheduleCreate,
  ScheduleUpdate,
  SearchParams,
  SearchResult,
  SearchResults,
  SessionDetail,
  SessionParams,
  SessionSummary,
  SpanNode,
  StateEntry,
  StateSetRequest,
  TimelineEvent,
  TimelineMeta,
  TimelineParams,
  TimelineResponse,
  TopSession,
  TraceDetail,
  TraceParams,
  TraceSummary,
  TriggerResponse,
} from "./types.ts";
